### ISSUE TITLE
Reference for Young's Thesis

### ISSUE THREAD

**Issue by ldhulipala** [creisle/pq-trees#1]
Hi Caralyn,

I'm a graduate student interested in PQ-trees. I came across your repo and was wondering whether you have an electronic copy of Young's thesis, since it seems to be pretty hard to find online. I thought I would ask to see if you still have a copy of her thesis available, or some resources that describe her approach in more detail.

Best,
Laxman

**Comment by creisle** [comment]
Sorry I did at one point, but unfortunately I don't anymore. I had a HD crash shortly after I switched projects. I do remember when I found it originally, it was through my university's library electronic records systems.

**Comment by ldhulipala** [comment]
Thanks for letting me know. If I get ahold of a copy I will make sure to upload it somewhere online (will post back here).
